[platformio]

[env:sphec_meter]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = no_ota.csv
lib_deps =
    bblanchon/ArduinoJson@^6.19.4
    adafruit/Adafruit INA219
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/RTClib
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^4.0.4
    adafruit/DHT sensor library @ ^1.4.6
    me-no-dev/ESPAsyncWebServer@^1.2.4
    me-no-dev/AsyncTCP@^1.1.1
    marvinroger/AsyncMqttClient@^0.9.0
    greiman/SdFat @ ^2.3.0
    kosme/arduinoFFT @ ^2.0.4